import type { Book } from "@/features/expressCheckout/types/express";

// Catalog seeded from the PageTurner Bookshop design. Each book carries a real ISBN that keys its
// bundled cover image (`coverImageUrl` → `public/covers/{isbn}.jpg`, downloaded once from Open Library);
// the `c1 → c2` gradient is the fallback cover shown when the image is missing/unreachable. Prices are
// display values in USD.
export const BOOKS: Book[] = [
  { id: 1, title: "The Midnight Library", author: "Matt Haig", genre: "Literary fiction", price: 16.99, rating: 4.7, reviews: 2431, c1: "#3B4A6B", c2: "#1E2740", isbn: "9780525559474", description: "Somewhere between life and death stands a library, and every book on its shelves is a life Nora Seed might have lived. As she wanders its endless aisles, undoing her regrets one choice at a time, she has to decide what makes a life truly worth living. A tender, big-hearted fable about second chances and the roads not taken." },
  { id: 2, title: "Atomic Habits", author: "James Clear", genre: "Self improvement", price: 18.5, rating: 4.8, reviews: 5892, c1: "#C56B4A", c2: "#8E4227", isbn: "9780735211292", description: "Real change doesn't come from massive overhauls but from tiny habits repeated until they compound. James Clear unpacks the science of how good behaviors take root and bad ones fall away, then hands you a clear, step-by-step system for getting one percent better every day. Equal parts psychology and practical toolkit." },
  { id: 3, title: "Project Hail Mary", author: "Andy Weir", genre: "Science fiction", price: 17.99, rating: 4.8, reviews: 3764, c1: "#2B6E6A", c2: "#14403D", isbn: "9780593135204", description: "A lone astronaut wakes millions of miles from home with no memory of who he is or why he's there, only the slowly dawning realization that he is humanity's last hope. What follows is a nail-biting puzzle of science, improvisation, and one gloriously unexpected friendship. Andy Weir at his funniest, smartest, and most thrilling." },
  { id: 4, title: "Seven Husbands of Evelyn Hugo", author: "Taylor Jenkins Reid", genre: "Historical fiction", price: 16.99, rating: 4.7, reviews: 4123, c1: "#8E3B5C", c2: "#5C2138", isbn: "9781501139239", description: "Aging and famously reclusive, Hollywood legend Evelyn Hugo is finally ready to tell the truth about her glamorous, scandalous life, and she's chosen an unknown magazine writer to hear it. As the glitter peels back to reveal ambition, sacrifice, and a love she hid for decades, the reason she picked this reporter becomes devastatingly clear. Impossible to put down." },
  { id: 5, title: "Educated", author: "Tara Westover", genre: "Memoir", price: 18.99, rating: 4.8, reviews: 6234, c1: "#6E7F5B", c2: "#454F37", isbn: "9780399590504", description: "Raised by survivalist parents in the mountains of Idaho, Tara Westover never set foot in a classroom until she was seventeen. Her journey from that isolated world to a Cambridge PhD is a staggering account of self-invention, and of the painful price of leaving your family behind to find yourself. Fierce, honest, and unforgettable." },
  { id: 6, title: "The Thursday Murder Club", author: "Richard Osman", genre: "Mystery", price: 17.5, rating: 4.6, reviews: 3891, c1: "#B8894A", c2: "#7E5A28", isbn: "9781984880963", description: "In a peaceful retirement village, four sharp-witted friends meet every week to pick apart unsolved crimes for fun. Then a real body turns up on their doorstep, and the amateurs find themselves in a very live investigation, armed with nothing but cunning, charm, and decades of being underestimated. Witty, warm, and deviously clever." },
  { id: 7, title: "Klara and the Sun", author: "Kazuo Ishiguro", genre: "Literary fiction", price: 16.5, rating: 4.5, reviews: 2987, c1: "#C9A24B", c2: "#95712A", isbn: "9780593318171", description: "Klara is an Artificial Friend with extraordinary powers of observation, watching the world from a store window as she waits to be chosen. When a young girl finally takes her home, Klara's fierce, uncomprehending love raises quiet and unsettling questions about what it really means to be human. A luminous, tender fable from a Nobel laureate." },
  { id: 8, title: "Circe", author: "Madeline Miller", genre: "Mythology", price: 17.99, rating: 4.8, reviews: 5140, c1: "#8E3B5C", c2: "#5C2138", isbn: "9780316556347", description: "Born a lesser goddess in the halls of the sun god Helios, Circe is scorned and overlooked until she discovers a mortal gift for witchcraft, and is banished to a deserted island for it. There she hones her powers and crosses paths with gods and heroes, until she must finally choose between the immortals she came from and the humans she has come to love. Bold, spellbinding, and gorgeously told." },
  { id: 9, title: "A Gentleman in Moscow", author: "Amor Towles", genre: "Historical fiction", price: 18.25, rating: 4.8, reviews: 4462, c1: "#3B4A6B", c2: "#1E2740", isbn: "9780670026197", description: "Sentenced to house arrest in a grand Moscow hotel in 1922, Count Alexander Rostov must build a life within its walls while history convulses in the streets outside. Across three decades he finds unexpected purpose, friendship, and even love in the smallest of worlds. A witty, elegant, and deeply humane novel about grace under confinement." },
  { id: 10, title: "The Song of Achilles", author: "Madeline Miller", genre: "Mythology", price: 16.99, rating: 4.7, reviews: 6021, c1: "#2B6E6A", c2: "#14403D", isbn: "9780062060624", description: "Awkward, exiled young prince Patroclus is drawn to the golden, godlike Achilles, and their boyhood bond deepens into a love tested by pride, prophecy, and the ten-year siege of Troy. Retelling the Iliad from the inside, Madeline Miller turns ancient myth into an aching, intimate human story of devotion and fate. Radiant and heartbreaking." },
  { id: 11, title: "Braiding Sweetgrass", author: "Robin Wall Kimmerer", genre: "Nature essays", price: 19.0, rating: 4.9, reviews: 3357, c1: "#6E7F5B", c2: "#454F37", isbn: "9781571313560", description: "A botanist and enrolled member of the Potawatomi Nation, Robin Wall Kimmerer braids together Indigenous wisdom, rigorous plant science, and the lessons the living world offers when we pay attention. The result is a generous meditation on reciprocity, gratitude, and how we might live in true relationship with the earth. Quietly revolutionary and profoundly hopeful." },
  { id: 12, title: "Tomorrow, and Tomorrow, and Tomorrow", author: "Gabrielle Zevin", genre: "Contemporary fiction", price: 18.99, rating: 4.6, reviews: 4890, c1: "#C56B4A", c2: "#8E4227", isbn: "9780593321201", description: "Sam and Sadie meet as kids in a hospital game room and reunite years later to build video games together, chasing that first pure feeling of play. Across thirty years of dazzling success, betrayal, and heartbreak, theirs becomes a love story that isn't quite romance, but something rarer and more enduring. A sweeping novel about art, ambition, and the people who truly see us." },
  { id: 13, title: "Where the Crawdads Sing", author: "Delia Owens", genre: "Literary fiction", price: 17.99, rating: 4.8, reviews: 7218, c1: "#2B6E6A", c2: "#14403D", isbn: "9780735219090", description: "Abandoned young and left to raise herself in the marshes of North Carolina, Kya Clark becomes a mystery to the town that shuns her, the so-called Marsh Girl. When a local golden boy turns up dead, suspicion falls squarely on her. Part coming-of-age story, part murder mystery, part love letter to the natural world, it's as haunting as it is beautiful." },
  { id: 14, title: "The Silent Patient", author: "Alex Michaelides", genre: "Psychological thriller", price: 16.99, rating: 4.6, reviews: 6890, c1: "#3B4A6B", c2: "#1E2740", isbn: "9781250301697", description: "Alicia Berenson shoots her husband five times and then never speaks another word, a silence that turns her into a national obsession. Psychotherapist Theo Faber is determined to be the one who finally makes her talk, but his fixation drags him toward a truth he never saw coming. A twisty, addictive psychological thriller with a jaw-dropping final act." },
  { id: 15, title: "It Ends with Us", author: "Colleen Hoover", genre: "Romance", price: 16.5, rating: 4.7, reviews: 8342, c1: "#8E3B5C", c2: "#5C2138", isbn: "9781501110368", description: "Lily has worked hard for the life she always wanted, and falling for charming neurosurgeon Ryle feels like the reward she's earned. But when her first love unexpectedly resurfaces, everything she believed about Ryle, and about the patterns she swore she'd never repeat, is thrown into doubt. A brave, deeply emotional story about love, courage, and breaking the cycle." },
  { id: 16, title: "The Alchemist", author: "Paulo Coelho", genre: "Fable", price: 15.99, rating: 4.7, reviews: 9105, c1: "#C9A24B", c2: "#95712A", isbn: "9780061122415", description: "Santiago, a young Andalusian shepherd, sets out for the Egyptian pyramids after a recurring dream of hidden treasure. His journey across the desert, guided by omens and a mysterious alchemist, slowly becomes a quest for something far more valuable than gold. A luminous modern fable about listening to your heart and daring to follow your dream." },
  { id: 17, title: "Sapiens: A Brief History of Humankind", author: "Yuval Noah Harari", genre: "History", price: 22.99, rating: 4.8, reviews: 7643, c1: "#B8894A", c2: "#7E5A28", isbn: "9780062316097", description: "How did an unremarkable ape come to rule the planet? Yuval Noah Harari tells the sweeping story of our species, from the cognitive and agricultural revolutions to the rise of empires, money, religion, and modern science. Provocative and wildly readable, it reframes almost everything you thought you knew about being human." },
  { id: 18, title: "Dune", author: "Frank Herbert", genre: "Science fiction", price: 18.0, rating: 4.7, reviews: 8901, c1: "#C56B4A", c2: "#8E4227", isbn: "9780441172719", description: "On the desert world of Arrakis, the only source of the universe's most valuable substance, young Paul Atreides is thrust into a deadly game of empires, prophecy, and betrayal. As he takes refuge among the fierce, blue-eyed Fremen, he begins to fulfill a destiny far larger than himself. Frank Herbert's epic remains the towering masterpiece of science fiction." },
  { id: 19, title: "The Nightingale", author: "Kristin Hannah", genre: "Historical fiction", price: 17.99, rating: 4.8, reviews: 6754, c1: "#6E7F5B", c2: "#454F37", isbn: "9780312577223", description: "In Nazi-occupied France, two sisters take very different paths through the war, one sheltering the hunted at enormous personal risk, the other joining the armed resistance. Their intertwined stories form an unforgettable portrait of the quieter, often overlooked courage of women in wartime. Sweeping, harrowing, and profoundly moving." },
  { id: 20, title: "Normal People", author: "Sally Rooney", genre: "Contemporary fiction", price: 16.0, rating: 4.4, reviews: 5218, c1: "#3B4A6B", c2: "#1E2740", isbn: "9781984822178", description: "Connell and Marianne grow up in the same small Irish town, pretending not to know each other at school, yet bound by a connection neither can shake. Through university and the fraught years that follow, they drift together and apart, wounding and saving each other by turns. A piercingly intimate study of love, class, and the ways we let ourselves be known." },
  { id: 21, title: "The Vanishing Half", author: "Brit Bennett", genre: "Literary fiction", price: 17.5, rating: 4.6, reviews: 5987, c1: "#8E3B5C", c2: "#5C2138", isbn: "9780525536291", description: "Inseparable twin sisters run away from their small Southern Black community at sixteen and end up living in utterly different worlds, one embracing her heritage, the other quietly passing as white. Years later their daughters' lives collide, unraveling the secrets that all that distance was meant to protect. A stunning, generation-spanning novel about identity and the stories we tell to survive." },
  { id: 22, title: "Verity", author: "Colleen Hoover", genre: "Psychological thriller", price: 16.99, rating: 4.7, reviews: 8110, c1: "#2B6E6A", c2: "#14403D", isbn: "9781538724736", description: "Struggling writer Lowen is hired to finish the wildly successful series of injured author Verity Crawford. Digging through Verity's papers, she uncovers an unfinished manuscript, a private confession so disturbing it upends everything about the woman and the house Lowen is now living in. A dark, feverish thriller you won't be able to put down." },
  { id: 23, title: "The Four Winds", author: "Kristin Hannah", genre: "Historical fiction", price: 18.5, rating: 4.7, reviews: 5321, c1: "#C9A24B", c2: "#95712A", isbn: "9781250178602", description: "As the Great Depression and the Dust Bowl ravage the Texas panhandle, Elsa Martinelli faces an impossible choice: fight for the land and family she loves, or head west toward the uncertain promise of California. Her journey becomes an epic of hardship, dignity, and a mother's ferocious will to protect her children. A powerful tribute to the resilience of ordinary women." },
  { id: 24, title: "Little Fires Everywhere", author: "Celeste Ng", genre: "Contemporary fiction", price: 16.99, rating: 4.6, reviews: 6102, c1: "#C56B4A", c2: "#8E4227", isbn: "9780735224292", description: "In picture-perfect, meticulously planned Shaker Heights, the arrival of enigmatic artist Mia and her teenage daughter slowly upends the well-ordered life of the Richardson family. When a bitter custody battle divides the town, long-buried secrets and simmering resentments finally catch fire. A sharp, absorbing novel about motherhood, privilege, and the weight of the choices we make." },
  { id: 25, title: "Lessons in Chemistry", author: "Bonnie Garmus", genre: "Historical fiction", price: 18.99, rating: 4.8, reviews: 7455, c1: "#6E7F5B", c2: "#454F37", isbn: "9780385547345", description: "Brilliant chemist Elizabeth Zott is badly out of step with the male-dominated science of the early 1960s, so when she's pushed out of the lab and onto a daytime TV cooking show, she flatly refuses to play along. Instead she teaches a nation of housewives real chemistry, and the radical idea that they can change the status quo. Sharp, funny, and quietly furious." },
  { id: 26, title: "The Housemaid", author: "Freida McFadden", genre: "Psychological thriller", price: 15.99, rating: 4.6, reviews: 8967, c1: "#B8894A", c2: "#7E5A28", isbn: "9781538742570", description: "Desperate for a fresh start, Millie takes a live-in job cleaning the immaculate home of the wealthy Winchester family. But the attic room that locks only from the outside, the fear in Mrs. Winchester's eyes, and the household's flawless surface all hint at something far more sinister. A propulsive thriller with a twist you won't see coming." },
  { id: 27, title: "Fourth Wing", author: "Rebecca Yarros", genre: "Fantasy", price: 20.99, rating: 4.8, reviews: 9821, c1: "#8E3B5C", c2: "#5C2138", isbn: "9781649374042", description: "Twenty-year-old Violet Sorrengail was meant for a quiet life among books, until her commanding mother forces her into the brutal Basgiath War College to train as a dragon rider. There, cadets die more often than they graduate, the dragons refuse to bond with the weak, and a ruthless rival wants her dead, all while a real war closes in. Fierce, romantic, and impossible to stop reading." },
];

/** Cover gradient, matching the design's `coverStyle()` (150deg, c1 → c2). Fallback when no image. */
export function coverStyle(book: Pick<Book, "c1" | "c2">): { background: string } {
  return { background: `linear-gradient(150deg, ${book.c1}, ${book.c2})` };
}

/**
 * Real cover image, keyed by ISBN. Served from the demo's own `public/covers/{isbn}.jpg` (downloaded
 * once from `covers.openlibrary.org/b/isbn/{isbn}-L.jpg`) rather than hot-linking Open Library: that
 * endpoint 302-redirects to archive.org with a non-cacheable redirect, so the browser re-resolved it
 * on every reload. Same-origin static files are cached normally, load instantly, and work offline.
 * Missing files 404 → BookCover's `onError` reveals the gradient fallback. `BASE_URL` respects a
 * non-root deploy base.
 */
export function coverImageUrl(isbn: string): string {
  return `${import.meta.env.BASE_URL}covers/${isbn}.jpg`;
}

export function getBook(id: number | undefined): Book | undefined {
  return BOOKS.find((b) => b.id === id);
}
